In [1]:
import pandas as pd

In [14]:
csv_path = "base_desp.csv"
df = pd.read_csv(csv_path)
df.head()

,id_aluno,nome,idade,serie,sexo,nota_matematica,nota_portugues,frequencia
0,1,Pedro Lucas Vieira,11,6º Ano,Masculino,"4,1","3,8",63.7
1,2,Emanuelly Moreira,10,4º Ano,fem,"8,4",7.8,64.6
2,3,Murilo Nogueira,13,9º Ano,M,8.1,"6,5",68.4
3,4,Helena Oliveira,14,9º Ano,F,3.7,3.4,65.4
4,5,Alice Ribeiro,15,9º Ano,fem,2.7,"8,7",89.8

In [15]:
#tratamento da coluna de sexo
df['sexo'] = df['sexo'].str.replace(r'^[Mm].*', 'M', regex=True)
df['sexo'] = df['sexo'].str.replace(r'^[Ff].*', 'F', regex=True)

In [16]:
df.head() #verificação

,id_aluno,nome,idade,serie,sexo,nota_matematica,nota_portugues,frequencia
0,1,Pedro Lucas Vieira,11,6º Ano,M,"4,1","3,8",63.7
1,2,Emanuelly Moreira,10,4º Ano,F,"8,4",7.8,64.6
2,3,Murilo Nogueira,13,9º Ano,M,8.1,"6,5",68.4
3,4,Helena Oliveira,14,9º Ano,F,3.7,3.4,65.4
4,5,Alice Ribeiro,15,9º Ano,F,2.7,"8,7",89.8

In [18]:
# para contas, em py o ',' nao pode ser usado, entao mudei para '.' para depois retornar para ','
df['nota_matematica']=df['nota_matematica'].str.replace(',','.',regex=False)
df['nota_portugues']=df['nota_portugues'].str.replace(',','.',regex=False)
df.head()

,id_aluno,nome,idade,serie,sexo,nota_matematica,nota_portugues,frequencia
0,1,Pedro Lucas Vieira,11,6º Ano,M,4.1,3.8,63.7
1,2,Emanuelly Moreira,10,4º Ano,F,8.4,7.8,64.6
2,3,Murilo Nogueira,13,9º Ano,M,8.1,6.5,68.4
3,4,Helena Oliveira,14,9º Ano,F,3.7,3.4,65.4
4,5,Alice Ribeiro,15,9º Ano,F,2.7,8.7,89.8

In [22]:
df['nota_matematica'] = pd.to_numeric(df['nota_matematica'], errors='coerce')
df['nota_portugues'] = pd.to_numeric(df['nota_portugues'], errors='coerce')
df['frequencia'] = pd.to_numeric(df['frequencia'], errors='coerce')
df['media_notas'] = ((df['nota_matematica'] + df['nota_portugues'] + (df['frequencia'] / 10)) / 3 ).round(1)# criação da coluna media

In [23]:
df.head()

,id_aluno,nome,idade,serie,sexo,nota_matematica,nota_portugues,frequencia,media_notas
0,1,Pedro Lucas Vieira,11,6º Ano,M,4.1,3.8,63.7,4.8
1,2,Emanuelly Moreira,10,4º Ano,F,8.4,7.8,64.6,7.6
2,3,Murilo Nogueira,13,9º Ano,M,8.1,6.5,68.4,7.1
3,4,Helena Oliveira,14,9º Ano,F,3.7,3.4,65.4,4.5
4,5,Alice Ribeiro,15,9º Ano,F,2.7,8.7,89.8,6.8

In [25]:
df['aprovado'] = df['media_notas'].map(lambda x: 'Aprovado' if x > 7.0 else 'Reprovado') #criação da coluna aprovados

In [26]:
df.head()

,id_aluno,nome,idade,serie,sexo,nota_matematica,nota_portugues,frequencia,media_notas,aprovado
0,1,Pedro Lucas Vieira,11,6º Ano,M,4.1,3.8,63.7,4.8,Reprovado
1,2,Emanuelly Moreira,10,4º Ano,F,8.4,7.8,64.6,7.6,Aprovado
2,3,Murilo Nogueira,13,9º Ano,M,8.1,6.5,68.4,7.1,Aprovado
3,4,Helena Oliveira,14,9º Ano,F,3.7,3.4,65.4,4.5,Reprovado
4,5,Alice Ribeiro,15,9º Ano,F,2.7,8.7,89.8,6.8,Reprovado

In [33]:
#transformo tudo para string
df['nota_matematica'] = df['nota_matematica'].astype(str)
df['nota_portugues'] = df['nota_portugues'].astype(str)
df['frequencia'] = df['frequencia'].astype(str)
df['media_notas'] = df['media_notas'].astype(str)

#formatação dos numeros de '.' para ','
df['nota_matematica']=df['nota_matematica'].str.replace('.',',',regex=False)
df['nota_portugues']=df['nota_portugues'].str.replace('.',',',regex=False)
df['frequencia']=df['frequencia'].str.replace('.',',',regex=False)
df['media_notas']=df['media_notas'].str.replace('.',',',regex=False)
df.head()

,id_aluno,nome,idade,serie,sexo,nota_matematica,nota_portugues,frequencia,media_notas,aprovado
0,1,Pedro Lucas Vieira,11,6º Ano,M,"4,1","3,8","63,7","4,8",Reprovado
1,2,Emanuelly Moreira,10,4º Ano,F,"8,4","7,8","64,6","7,6",Aprovado
2,3,Murilo Nogueira,13,9º Ano,M,"8,1","6,5","68,4","7,1",Aprovado
3,4,Helena Oliveira,14,9º Ano,F,"3,7","3,4","65,4","4,5",Reprovado
4,5,Alice Ribeiro,15,9º Ano,F,"2,7","8,7","89,8","6,8",Reprovado

In [36]:
df.to_csv('base_pronta.csv', index=False) #salvando alterações